### ISSUE TITLE
strange behaviour when displaying laserscans

### ISSUE THREAD

**Issue by cblesing** [ros-visualization/rviz#1523] opened 2020-07-02 10:44 UTC
Hey everyone,

since i use noetic i have a strange behaviour in rviz. I'm not able to visualize a laserscan, both from real sensor data (SICK S300) and from a recorded bag file. Rviz says that scans are received and all tfs are fine. The rostopic echo tells me that everything is fine. Header looks good, included range data too. Maybe this issue is related to #1508. Even stranger is that very rarely points are displayed (image 1). But not all of them. The scanner has a fov of 180° and works fine for years with melodic.  

![Screenshot from 2020-07-02 12-37-43](https://user-images.githubusercontent.com/31893608/86349124-f31f0480-bc60-11ea-9550-993d06cb7e2b.png)
Don't worry about the tf warning in the first image. Thats only because no slam node is running and therefore no transform from map to odom frame is available. But this should not matter, selected frame is base_link.

If i run a slam node a perfect map is build up (image 2). In this image you can see exactly one point from the scan that is displayed. Has anyone an idea??
 
![Screenshot from 2020-07-02 12-38-20](https://user-images.githubusercontent.com/31893608/86349466-73456a00-bc61-11ea-9bb8-3b311569d4b1.png)

### My environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
[ INFO] [1593684896.992188484]: rviz version 1.14.0
[ INFO] [1593684896.992224227]: compiled against Qt version 5.12.8
[ INFO] [1593684896.992234742]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1593684897.000585023]: Forcing OpenGl version 0.
[ INFO] [1593684897.395518159, 1593609599.094613020]: Stereo is NOT SUPPORTED
[ INFO] [1593684897.395573937, 1593609599.094613020]: OpenGl version: 4.6 (GLSL 4.6).

**Comment by rhaschke** [comment] 2020-07-02 11:50
Duplicate of #1511, which is fixed and released (but not yet synced). I suggest to use the [ros-testing repos](http://wiki.ros.org/TestingRepository) to get the released version already now.

**Closed by rhaschke** 2020-07-02 11:50 UTC
