### ISSUE TITLE
Laser scan of rviz can not display information when the object is more than one meter

### ISSUE THREAD

**Issue by zx595306686** [ros-visualization/rviz#1524] opened 2020-07-03 13:42 UTC
### Your environment
* OS Version: e.g. Ubuntu 20.04
* ROS Distro: noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
 [ INFO] [1593784302.745425622]: rviz version 1.14.0
[ INFO] [1593784302.745487199]: compiled against Qt version 5.12.8
[ INFO] [1593784302.745504793]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1593784302.755674484]: Forcing OpenGl version 0.
[ INFO] [1593784304.360898875]: Stereo is NOT SUPPORTED
[ INFO] [1593784304.361005013]: OpenGl version: 2.1 (GLSL 1.2).

**Comment by rhaschke** [comment] 2020-07-03 13:56
Duplicate of #1511, which is fixed and released (but not yet synced). I suggest to use the [ros-testing repos](http://wiki.ros.org/TestingRepository) to get the released version already now.

**Closed by rhaschke** 2020-07-03 13:56 UTC
