### ISSUE TITLE
TF Display crashes on reset

### ISSUE THREAD

**Issue by dgossow** [ros-visualization/rviz#616] opened 2013-03-18 22:50 UTC
The tf display causes a segfault when clicking the "reset" button in the bottom-left window corner.

@jkammerl please add backtrace

**Comment by arntanguy** [comment] 2015-10-10 02:25
Merged #926 should solve this.

**Comment by wjwwood** [comment] 2015-10-12 18:28
I just tried this and couldn't reproduce it either, so I'm going to close this. Anyone please comment here if you run into this issue.

**Closed by wjwwood** 2015-10-12 18:28 UTC
Labels: bug
