### ISSUE TITLE
rviz config file does not enable/disable display visibility inside camera display correctly

### ISSUE THREAD

**Issue by mateiciocarlie** [ros-visualization/rviz#610] opened 2013-03-15 22:30 UTC
For example, rosrun rviz rviz -d config2.rviz dos not produce consistent enabling/disabling of:
- HeadCamera/Visibility/Robot/RobotModel
- HeadCamera/Visibility/Navigation/Map

config2.rviz is below (Github won't let me attach the file...)

```
Panels:
- Class: rviz/Displays
  Help Height: 156
  Name: Displays
  Property Tree Widget: {Expanded: null, Splitter Ratio: 0.645977}
  Tree Height: 438
- Class: rviz/Views
  Expanded: [/Current View1]
  Name: Views
  Splitter Ratio: 0.5
- {Class: rviz/Time, Experimental: false, Name: Time, SyncMode: 0, SyncSource: Kinect
    Stream}
- Class: rviz/Tool Properties
  Expanded: [/Navigate To1, /Set Gripper1, /Look At1, /2D Pose Estimate1]
  Name: Tool Properties
  Splitter Ratio: 0.5
Visualization Manager:
  Class: ''
  Displays:
  - Alpha: 0.5
    Cell Size: 0.2
    Class: rviz/Grid
    Color: 249; 249; 255
    Enabled: true
    Line Style: {Line Width: 0.03, Value: Lines}
    Name: Grid
    Normal Cell Count: 0
    Offset: {X: 0, Y: 0, Z: 0.05}
    Plane: XY
    Plane Cell Count: 50
    Reference Frame: <Fixed Frame>
    Value: true
  - Class: rviz/Group
    Displays:
    - {Class: rviz/InteractiveMarkers, Enabled: true, Name: Pick Up Objects, Show Axes: false,
      Show Descriptions: true, Show Visual Aids: false, Update Topic: /interactive_manipulation/update,
      Value: true}
    - {Class: rviz/InteractiveMarkers, Enabled: true, Name: PR2 Teleop (Transparent),
      Show Axes: false, Show Descriptions: false, Show Visual Aids: true, Update Topic: /pr2_marker_control_transparent/update,
      Value: true}
    - {Class: rviz/InteractiveMarkers, Enabled: true, Name: Interactive Gripper, Show Axes: false,
      Show Descriptions: true, Show Visual Aids: true, Update Topic: /interactive_gripper/update,
      Value: true}
    - {Class: rviz/InteractiveMarkers, Enabled: true, Name: PR2 Nav, Show Axes: false,
      Show Descriptions: true, Show Visual Aids: false, Update Topic: /pr2_nav_marker_control/update,
      Value: true}
    - {Class: rviz/InteractiveMarkers, Enabled: false, Name: PR2 Teleop, Show Axes: false,
      Show Descriptions: true, Show Visual Aids: false, Update Topic: /pr2_marker_control/update,
      Value: false}
    Enabled: true
    Name: Interactive Markers
  - Class: rviz/Group
    Displays:
    - Alpha: 1
      Class: pr2_interactive_manipulation_frontend/InvisibleRobot
      Collision Enabled: false
      Enabled: true
      Links:
        base_bellow_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        base_footprint: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        base_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        double_stereo_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_mount_kinect_ir_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_mount_kinect_rgb_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_mount_prosilica_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_plate_frame: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_tilt_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_elbow_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_forearm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_forearm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_l_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_l_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_gripper_motor_accelerometer_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_gripper_palm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_r_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_r_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_shoulder_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_shoulder_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_upper_arm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_upper_arm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_wrist_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_wrist_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        laser_tilt_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_elbow_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_forearm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_forearm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_l_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_l_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_gripper_motor_accelerometer_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_gripper_palm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_r_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_r_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_shoulder_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_shoulder_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_upper_arm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_upper_arm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_wrist_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_wrist_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        sensor_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        torso_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
      Name: InvisibleRobot
      Robot Description: robot_description
      TF Prefix: ''
      Update Interval: 0
      Value: true
      Visual Enabled: true
    - Alpha: 1
      Class: rviz/RobotModel
      Collision Enabled: false
      Enabled: true
      Links:
        base_bellow_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        base_footprint: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        base_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        bl_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        br_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        double_stereo_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fl_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_l_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_r_wheel_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        fr_caster_rotation_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_mount_kinect_ir_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_mount_kinect_rgb_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_mount_prosilica_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        head_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_plate_frame: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        head_tilt_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_elbow_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_forearm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_forearm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_l_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_l_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_gripper_motor_accelerometer_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_gripper_palm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_r_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_gripper_r_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        l_shoulder_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_shoulder_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_upper_arm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_upper_arm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_wrist_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        l_wrist_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        laser_tilt_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_elbow_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_forearm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_forearm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_l_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_l_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_gripper_motor_accelerometer_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_gripper_palm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_r_finger_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_gripper_r_finger_tip_link: {Alpha: 1, Show Axes: false, Show Trail: false,
          Value: true}
        r_shoulder_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_shoulder_pan_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_upper_arm_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_upper_arm_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_wrist_flex_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        r_wrist_roll_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        sensor_mount_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
        torso_lift_link: {Alpha: 1, Show Axes: false, Show Trail: false, Value: true}
      Name: RobotModel
      Robot Description: robot_description
      TF Prefix: ''
      Update Interval: 0
      Value: true
      Visual Enabled: true
    Enabled: true
    Name: Robot
  - Class: pr2_interactive_manipulation_frontend/PublishClickCamera
    Enabled: true
    Image Rendering: background and overlay
    Image Topic: /head_mount_kinect/rgb/image_color
    Name: Head Camera
    Near Clip Distance: 0.01
    Overlay Alpha: 0.5
    Publish Click Topic: /interactive_manipulation_image_click
    Queue Size: 2
    Show Panel: false
    Transport Hint: compressed
    Value: true
    Visibility:
      Debug Displays: {Attached Objects: true, Base Laser: true, Grasp Execution Markers: true,
        Grasp Markers: true, Octomap Point Cloud: true, Planning Scene Markers: true,
        Robot Model: true, Tabletop Segmentation Markers: true, Value: true}
      Grid: true
      Interactive Markers: {Interactive Gripper: true, PR2 Nav: true, PR2 Teleop: true,
        PR2 Teleop (Transparent): true, Pick Up Objects: true, Value: true}
      Kinect Stream: false
      Navigation: {Map: false, Nav Global Path: true, Nav Obstacles: true, Value: true}
      Panels: {CameraFocusFrontend: true, Manipulation: true, Object Detection: true,
        Object Recognition: true, Value: true}
      People Tracking: {InteractiveMarkers: true, Value: true}
      Robot: {InvisibleRobot: true, RobotModel: false, Value: true}
      Value: true
    Zoom Factor: 1
  - Alpha: 1
    Auto Size: {Auto Size Factor: 1, Value: true}
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds: {Max Value: 10, Min Value: -10, Value: true}
    Axis: Z
    Channel Name: intensity
    Class: rviz/DepthCloud
    Color: 255; 255; 255
    Color Image Topic: /head_mount_kinect/rgb/image_color
    Color Transformer: RGB8
    Color Transport Hint: compressed
    Decay Time: 0
    Depth Map Topic: /head_mount_kinect/depth_registered/image
    Depth Map Transport Hint: compressedDepth
    Enabled: true
    Max Color: 255; 255; 255
    Max Intensity: 4096
    Min Color: 0; 0; 0
    Min Intensity: 0
    Name: Kinect Stream
    Occlusion Compensation: {Occlusion Time-Out: 30, Value: false}
    Position Transformer: XYZ
    Queue Size: 3
    Selectable: true
    Size (Pixels): 3
    Style: Flat Squares
    Topic Filter: true
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Class: rviz/Group
    Displays:
    - {Class: object_recognition_gui/ObjectRecognition, Enabled: true, Name: Object
        Recognition}
    - {Class: pr2_interactive_manipulation_frontend/InteractiveManipulationFrontend,
      Enabled: true, Name: Manipulation}
    - {Class: pr2_interactive_object_detection_frontend/InteractiveObjectDetection,
      Enabled: true, Name: Object Detection}
    - {Class: pr2_interactive_manipulation_frontend/CameraFocusFrontend, Command topic: /rviz/camera_placement,
      Enabled: true, Name: CameraFocusFrontend, Value: true}
    Enabled: true
    Name: Panels
  - Class: rviz/Group
    Displays:
    - Alpha: 1
      Class: rviz/RobotModel
      Collision Enabled: false
      Enabled: false
      Links: {}
      Name: Robot Model
      Robot Description: robot_description
      TF Prefix: ''
      Update Interval: 0
      Value: false
      Visual Enabled: true
    - Class: rviz/Marker
      Enabled: false
      Marker Topic: /grasp_markers
      Name: Grasp Markers
      Namespaces: {}
      Queue Size: 100
      Value: false
    - Class: rviz/Marker
      Enabled: false
      Marker Topic: /object_manipulator/grasp_execution_markers
      Name: Grasp Execution Markers
      Namespaces: {}
      Queue Size: 100
      Value: false
    - Class: rviz/Marker
      Enabled: false
      Marker Topic: /attached_objects
      Name: Attached Objects
      Namespaces: {}
      Queue Size: 100
      Value: false
    - Class: rviz/Marker
      Enabled: false
      Marker Topic: /planning_scene_markers
      Name: Planning Scene Markers
      Namespaces: {}
      Queue Size: 100
      Value: false
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds: {Max Value: 2.8125, Min Value: -0.0375, Value: true}
      Axis: Z
      Channel Name: intensity
      Class: rviz/PointCloud2
      Color: 255; 255; 255
      Color Transformer: FlatColor
      Decay Time: 0
      Enabled: false
      Max Color: 255; 255; 255
      Max Intensity: 4096
      Min Color: 0; 0; 0
      Min Intensity: 0
      Name: Octomap Point Cloud
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.025
      Style: Boxes
      Topic: /octomap_point_cloud
      Use Fixed Frame: true
      Use rainbow: true
      Value: false
    - Class: rviz/Marker
      Enabled: false
      Marker Topic: /tabletop_segmentation_markers
      Name: Tabletop Segmentation Markers
      Namespaces: {}
      Queue Size: 100
      Value: false
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds: {Max Value: 10, Min Value: -10, Value: true}
      Axis: Z
      Channel Name: intensity
      Class: rviz/LaserScan
      Color: 255; 255; 255
      Color Transformer: Intensity
      Decay Time: 0
      Enabled: false
      Max Color: 255; 255; 255
      Max Intensity: 4096
      Min Color: 0; 0; 0
      Min Intensity: 0
      Name: Base Laser
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.01
      Style: Billboards
      Topic: /base_scan_throttled
      Use Fixed Frame: true
      Use rainbow: true
      Value: false
    Enabled: false
    Name: Debug Displays
  - Class: rviz/Group
    Displays:
    - {Class: rviz/InteractiveMarkers, Enabled: true, Name: InteractiveMarkers, Show Axes: false,
      Show Descriptions: true, Show Visual Aids: false, Update Topic: '', Value: true}
    Enabled: false
    Name: People Tracking
  - Class: rviz/Group
    Displays:
    - {Alpha: 0.7, Class: rviz/Map, Draw Behind: false, Enabled: true, Name: Map,
      Topic: /map, Value: false}
    - {Alpha: 1, Class: rviz/GridCells, Color: 255; 255; 127, Enabled: true, Name: Nav
        Obstacles, Topic: /move_base_node/local_costmap/obstacles, Value: false}
    - {Alpha: 1, Buffer Length: 1, Class: rviz/Path, Color: 25; 255; 0, Enabled: true,
      Name: Nav Global Path, Topic: /move_base_node/NavfnROS/plan, Value: false}
    Enabled: true
    Name: Navigation
  Enabled: true
  Global Options: {Background Color: 48; 48; 48, Fixed Frame: /map}
  Name: root
  Tools:
  - {Class: rviz/Interact, Hide Inactive Objects: true}
  - {Class: rviz/MoveCamera}
  - {Class: rviz/FocusCamera}
  - {Class: pr2_interactive_manipulation_frontend/NavigateTo, Single click: true,
    Topic: /rviz/navigate_to}
  - {Class: pr2_interactive_manipulation_frontend/SetGripper, Single click: true,
    Topic: /rviz/set_gripper}
  - {Class: pr2_interactive_manipulation_frontend/LookAt, Single click: true, Topic: /rviz/look_here}
  - {Class: rviz/SetInitialPose, Topic: initialpose}
  Value: true
  Views:
    Current:
      Class: rviz_animated_view_controller/Animated
      Control Mode: Orbit
      Distance: 2.64189
      Eye: {X: 0.238192, Y: 2.63682, Z: 0.863985}
      Focus: {X: 0.354214, Y: -0.00248102, Z: 0.849285}
      Maintain Vertical Axis: true
      Mouse Enabled: true
      Name: Current View
      Near Clip Distance: 0.01
      Placement Topic: /rviz/camera_placement
      Target Frame: <Fixed Frame>
      Transition Time: 0.5
      Up: {X: 0.00486814, Y: -0.00535529, Z: 0.999974}
      Value: Animated (rviz_animated_view_controller)
    Saved: null
Window Geometry:
  Displays: {collapsed: false}
  Head Camera: {collapsed: false}
  Height: 1064
  Hide Left Dock: false
  Hide Right Dock: false
  Manipulation: {collapsed: false}
  Object Detection: {collapsed: false}
  QMainWindow State: 000000ff00000000fd00000003000000000000013e000002bcfc0200000007fc0000014e000000ad0000000000fffffffa000000000100000001fb000000300049006e0074006500720061006300740069007600650020004d0061006e006900700075006c006100740069006f006e0100000000ffffffff0000000000000000fb000000160048006500610064002000430061006d0065007200610000000041000001190000001600fffffffb0000000800540069006d0065020000028f000003f2000002c700000046fb000000380049006e0074006500720061006300740069007600650020004f0062006a00650063007400200044006500740065006300740069006f006e0100000268000000cc0000000000000000fb0000000a0049006d0061006700650000000221000000b80000000000000000fb0000000a0049006d006100670065020000046900000366000002f80000028bfb0000001e0054006f006f006c002000500072006f0070006500720074006900650073000000023f0000009a0000006400ffffff000000010000013e000003a9fc0200000003fc00000041000002b1000000fb0100001dfa000000010100000002fb0000000a005600690065007700730100000000ffffffff0000010f00fffffffb000000100044006900730070006c00610079007301000006080000011d0000010f00fffffffc000002f8000000f2000000db0100001dfa000000010100000002fb00000020004f0062006a00650063007400200044006500740065006300740069006f006e0100000000ffffffff000000cc00fffffffb00000018004d0061006e006900700075006c006100740069006f006e010000034f0000013e0000013e00fffffffc00000041000003740000000000fffffffa000000000100000001fb0000001200530065006c0065006300740069006f006e0100000000ffffffff0000000000000000000000020000019a00000031fc0100000002fb0000001800430061006d00650072006100200046006f00630075007301000001440000019a0000000000000000fb0000002a00430061006d00650072006100200046006f006300750073002000460072006f006e00740065006e006401000001440000029c000000000000000000000502000003a900000001000000020000000100000002fc00000003000000020000000000000002000000020000000a0054006f006f006c007301000000000000034f00000000000000000000001600430061006d0065007200610046006f006300750073010000034f0000015500000000000000000000000300000000
  Time: {collapsed: false}
  Tool Properties: {collapsed: false}
  Views: {collapsed: false}
  Width: 1612
  X: 174
  Y: -152
```

**Comment by DLu** [comment] 2015-07-10 20:04
Another year on, and this is still an issue. I believe it keys off of the mysterious `QMainWindow State` variable. 

This configuration (in indigo) shows rviz without the selection panel displayed (i.e. it is properly collapsed):
```
Panels:
  - Class: rviz/Selection
    Name: Selection
Window Geometry:
  QMainWindow State: 000000ff00000000fd00000001000000000000029c0000035ffc0200000006fb000000180052006f0062006f0074002000430061006d0065007200610000000044000000890000001800fffffffb000000100044006900730070006c00610079007301000000440000015f000000d400fffffffb0000001200530065006c0065006300740069006f006e0000000160000000890000006000fffffffb0000001e0054006f006f006c002000500072006f007000650072007400690065007301000001a9000000d30000006000fffffffb0000000a00560069006500770073010000028200000121000000b000fffffffb0000000800540069006d006500000003460000005d0000004000ffffff000004de0000035f00000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
  Selection:
    collapsed: false
```

This configuration shows rviz with the selection panel (i.e. not properly collapsed).
```
Panels:
  - Class: rviz/Selection
    Name: Selection
Window Geometry:
  Selection:
    collapsed: false
```

Can anyone with knowledge of the inner workings of rviz say what the QMainWindow variable does?

**Comment by wjwwood** [comment] 2015-07-10 20:40
I would guess that it is the output from `QMainWindow::saveState`:

http://doc.qt.io/qt-4.8/qmainwindow.html#saveState

I've never worked on that part of rviz though.

**Comment by Simonmaignan** [comment] 2023-10-27 15:05
Did anyone fix this issue or find a way to bypass it?

**Comment by rhaschke** [comment] 2023-10-29 09:22
I can't reproduce the issue in Noetic. Visibility of displays within the Camera is correctly saved and restored:
![image](https://github.com/ros-visualization/rviz/assets/5376030/db3b5a1d-473b-4099-97ef-72010d7fe542)

I'm closing this issue. @Simonmaignan, please open a new issue describing exactly your problem.

**Closed by rhaschke** 2023-10-29 09:22 UTC
Labels: bug, backlog

**Comment by Simonmaignan** [comment] 2023-11-02 08:38
Thanks for testing @rhaschke .
Indeed, the Visibility info are indeed retrieved for the `Camera` plugin.
However it's not working for my user defined plugin so I must set the visibility property wrongly inside my code.

Would you have an example of setting up and using a `DisplayGroupVisibilityProperty`?

**Comment by rhaschke** [comment] 2023-11-02 09:21
Just have a look into the `Camera` plugin? Do you define custom load/save methods? Do they call the base class methods?

**Comment by Simonmaignan** [comment] 2023-11-02 15:36
Thanks @rhaschke .
I haven't found any implementation difference between my user defined plugin and the `rviz/CameraDisplay` w.r.t. the setup of `DisplayGroupVisibilityProperty`.
I noticed that my plugin cannot read the `"Visibility"` parameters from the `.rviz` config file if it contains some deactivated `Group`. However, this behavior is not reproducible with the `rviz/CameraDisplay` so there is probably something wrong with my implementation.

Deleting the deactivated `Group` from my `.rviz` config file allowed me to contourn this issue for now.
I'll dig deeper into the issue later.
