### ISSUE TITLE
Markers not rendered properly on ROS Noetic

### ISSUE THREAD

**Issue by VladyslavUsenko** [ros-visualization/rviz#1563] opened 2020-11-22 16:41 UTC
Markers (CUBE_LIST, SPHERE_LIST) not rendered properly with ROS Noetic. Instead of actual primitives, they are rendered as white dots. The same markers work fine with ROS Melodic. See the attached screenshots (top - melodic, bottom noetic):

![melodic_rviz](https://user-images.githubusercontent.com/2621267/99909385-81675600-2ce8-11eb-94cb-2f539e9cc702.png)
![noetic_rviz](https://user-images.githubusercontent.com/2621267/99909390-862c0a00-2ce8-11eb-80b7-b0aae8cdb2e9.png )

The bag and rviz files for reproducing the issue are attached below: 

https://drive.google.com/file/d/1us-gtL9U1jAzFcq6WAl4wWNgKX6QEEPg/view?usp=sharing

[simulation.rviz.zip](https://github.com/ros-visualization/rviz/files/5579822/simulation.rviz.zip)

### Your environment
* OS Version: Ubuntu 20.04
* ROS Distro: Noetic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
```
[ INFO] [1606062535.201571365]: rviz version 1.14.1
[ INFO] [1606062535.201613247]: compiled against Qt version 5.12.8
[ INFO] [1606062535.201625189]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1606062535.209114479]: Forcing OpenGl version 0.
[ INFO] [1606062535.382282171]: Stereo is NOT SUPPORTED
[ INFO] [1606062535.382330846]: OpenGl version: 4.6 (GLSL 4.6).
```

**Comment by rhaschke** [comment] 2020-11-22 18:26
This looks like a duplicate of #1508. Please check the solution there: running rviz with option `--opengl 210`.

**Comment by VladyslavUsenko** [comment] 2020-11-22 19:34
Yes, `--opengl 210` fixes the issue. Thanks!

**Closed** 2020-11-22 19:37 UTC
