### ISSUE TITLE
RVIZ in ROS2 cannot find freeimage/freetype package

### ISSUE THREAD

**Issue by davidhuziji** [ros-visualization/rviz#1207] opened 2018-03-08 12:31 UTC
Hi, I'm cross compiling the latest ROS2 for arm platforms, following [https://github.com/ros2/ros2/tree/master/arm_crosscompilation](url).
However, I met a issue in RVIZ building. It says that the `freeimage` library cannot be found.

The error log shows as follow.
```
-- Could not find freeimage library
CMake Error at /home/davhu01/project/trustzone_dds/install/share/rviz_ogre_vendor/cmake/rviz_ogre_vendor-extras.cmake:89 (find_package):
  Could not find a package configuration file provided by "freetype" with any
  of the following names:

    freetypeConfig.cmake
    freetype-config.cmake

  Add the installation prefix of "freetype" to CMAKE_PREFIX_PATH or set
  "freetype_DIR" to a directory containing one of the above files.  If
  "freetype" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
 
/home/davhu01/project/trustzone_dds/install/share/rviz_ogre_vendor/cmake/rviz_ogre_vendorConfig.cmake:30 (include)
  CMakeLists.txt:23 (find_package)
-- Configuring incomplete, errors occurred!
```

I installed the `freeimage` and `freetype6`. But it still failed. Should I manually set the directory to `freeimage`/`freestype`?
I also tried [https://github.com/ros2/rviz/blob/ros2/README.md](url) but it neither work.

Could you please tell me how to fix this issue?
Thank you.

**Comment by mikaelarguedas** [comment] 2018-03-08 15:52
@davidhuziji thanks for reporting the issue. However, as this is a duplicate of https://github.com/ros2/rviz/issues/226 and not related to this repository I recommend to close this issue and to ask the question in a single place in the future

**Closed** 2018-03-08 16:27 UTC
