### ISSUE TITLE
window blinking while move out of the rviz window

### ISSUE THREAD

**Issue by lianghongzhuo** [ros-visualization/rviz#1557] opened 2020-11-15 19:12 UTC
Describe your issue here and explain how to reproduce it.

### Your environment
* Ubuntu 18.04
* ROS Distro: Melodic
* RViz 1.13.14, Qt, OGRE 1.9.0
  
When moving the mouse into rviz will display some help info as seen in the picture below:
![1](https://user-images.githubusercontent.com/16577120/99194211-56c44d00-277e-11eb-8007-89dea31439ce.png)
This is helpful, however the content `Left-Click:Rotate. Middle click: ....` is not at the same line as the `Reset` button on the left.
This will leads the screen blinking when moving the mouse out of the rviz window:
![2](https://user-images.githubusercontent.com/16577120/99194258-a145c980-277e-11eb-86f2-4b0169f99044.png)
As seen in the above picture, the help info disappears, which leads to a screen blinking.
I do not know whether it's only happening on my computer or a general issue.

Update:
I tried on another computer, this issue disppers, I think this might be related to my custom font settings.

**Comment by rhaschke** [comment] 2020-11-15 19:37
I cannot reproduce this issue as well. What exactly is blinking? The text or the window (as stated in title)?
What does it mean for the window to blink? Does the full window disappear and appear?

**Comment by lianghongzhuo** [comment] 2020-11-15 19:43
[screencast_00000.zip](https://github.com/ros-visualization/rviz/files/5543002/screencast_00000.zip)
Please see the screen shot video.

**Comment by rhaschke** [comment] 2020-11-16 07:46
Indeed, I think you have chosen a too large font for the text. This increases the widget size causing the flickering you observe.
Closing here.

**Closed by rhaschke** 2020-11-16 07:46 UTC

**Comment by lianghongzhuo** [comment] 2020-11-16 12:33
It's nothing to do with the font size, but the issuse with the font type. When I chagne the font to the ubuntu default font "ubuntu" the content now can display at the same line as the `reset` buttom. And then no more blinking of the screen.
